{% set name = "uchardet" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.freedesktop.org/software/uchardet/releases/uchardet-{{ version }}.tar.xz
  sha256: e97a60cfc00a1c147a674b097bb1422abd9fa78a2d9ce3f3fdcc2e78a34ac5f0

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  commands:
    - uchardet --version

about:
  home: https://github.com/freedesktop/uchardet/
  license: MPL-1.1
  license_family: MOZILLA
  license_file: COPYING
  summary: An encoding detector library that attempts to determine the encoding of the text
  description: |
    uchardet is an encoding detector library, which takes a sequence of bytes in an
    unknown character encoding without any additional information, and attempts to
    determine the encoding of the text. Returned encoding names are iconv-compatible.
    uchardet started as a C language binding of the original C++ implementation of
    the universal charset detection library by Mozilla. It can now detect more charsets,
    and more reliably than the original implementation.
  doc_url: https://www.freedesktop.org/wiki/Software/uchardet/
  dev_url: https://cgit.freedesktop.org/uchardet/uchardet/

extra:
  recipe-maintainers:
    - scopatz
    - cgr71ii
    - Tobias-Fischer
